# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/HP/Desktop/Degree/Nisan_final_project/Code_files/6. xdc_files/basys3_salsa_top.xdc

# IP: C:/Users/HP/Desktop/Degree/Nisan_final_project/Code_files/1.Verilog_Design_Code/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet
