# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/HP/Desktop/Degree/Nisan_final_project/vivado_implementation/top_interative_02/top_interative_02.runs/synth_1/top_salsa_xilinx.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 2
set_param checkpoint.writeSynthRtdsInDcp 1
set_param xicom.use_bs_reader 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/HP/Desktop/Degree/Nisan_final_project/vivado_implementation/top_interative_02/top_interative_02.cache/wt [current_project]
set_property parent.project_path C:/Users/HP/Desktop/Degree/Nisan_final_project/vivado_implementation/top_interative_02/top_interative_02.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/HP/Desktop/Degree/Nisan_final_project/vivado_implementation/top_interative_02/top_interative_02.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog C:/Users/HP/Desktop/Degree/Nisan_final_project/Code_files/3.Defines_file/salsa_defines.vh
read_verilog -library xil_defaultlib -sv {
  C:/Users/HP/Desktop/Degree/Nisan_final_project/Code_files/1.Verilog_Design_Code/constant_select.sv
  C:/Users/HP/Desktop/Degree/Nisan_final_project/Code_files/1.Verilog_Design_Code/d_r_c_round_interative.sv
  C:/Users/HP/Desktop/Degree/Nisan_final_project/Code_files/1.Verilog_Design_Code/hash_interative_with_d_r_c.sv
  C:/Users/HP/Desktop/Degree/Nisan_final_project/Code_files/1.Verilog_Design_Code/hex_to_SSD.sv
  C:/Users/HP/Desktop/Degree/Nisan_final_project/Code_files/1.Verilog_Design_Code/quarter_round.sv
  C:/Users/HP/Desktop/Degree/Nisan_final_project/Code_files/1.Verilog_Design_Code/salsa_fsm.sv
  C:/Users/HP/Desktop/Degree/Nisan_final_project/Code_files/1.Verilog_Design_Code/salsa_hash_interative_wrapper.sv
  C:/Users/HP/Desktop/Degree/Nisan_final_project/Code_files/1.Verilog_Design_Code/salsa_registers.sv
  C:/Users/HP/Desktop/Degree/Nisan_final_project/Code_files/1.Verilog_Design_Code/salsa_rx.sv
  C:/Users/HP/Desktop/Degree/Nisan_final_project/Code_files/1.Verilog_Design_Code/salsa_uart_tx.sv
  C:/Users/HP/Desktop/Degree/Nisan_final_project/Code_files/1.Verilog_Design_Code/salsa_xor_regs.sv
  C:/Users/HP/Desktop/Degree/Nisan_final_project/Code_files/1.Verilog_Design_Code/top_salsa_xilinx.sv
}
read_ip -quiet C:/Users/HP/Desktop/Degree/Nisan_final_project/Code_files/1.Verilog_Design_Code/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/HP/Desktop/my_vivado_pll.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/HP/Desktop/my_vivado_pll.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/HP/Desktop/my_vivado_pll.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/HP/Desktop/Degree/Nisan_final_project/Code_files/6. xdc_files/basys3_salsa_top.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/HP/Desktop/Degree/Nisan_final_project/Code_files/6. xdc_files/basys3_salsa_top.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/Users/HP/Desktop/Degree/Nisan_final_project/vivado_implementation/top_interative_02/top_interative_02.srcs/utils_1/imports/synth_1/top_salsa_xilinx.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top top_salsa_xilinx -part xc7a35tcpg236-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_salsa_xilinx.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file top_salsa_xilinx_utilization_synth.rpt -pb top_salsa_xilinx_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
